### ISSUE TITLE
Duplication of notebooks between doc and apps

### ISSUE THREAD

**Issue by ketch** [clawpack/apps#79]
Some notebooks -- like the 3 in the notebooks/geoclaw folder -- exist both in clawpack/doc and clawpack/apps.  This duplication is problematic since it means twice the work in maintaining them, if we remember to maintain them at all.  Note that at least one of these notebooks is currently broken (see #60).

I suggest that any given notebook be kept either in `doc` (if it serves primarily as documentation) or in `apps` (if it does not), but not both.

**Comment by ketch** [comment]
For the GeoClaw notebooks, I think they belong in the doc repo, but I defer to GeoClaw experts on that.

**Comment by mandli** [comment]
Given that these notebooks are intended as documentation I am in favor of moving them.

**Comment by bsc1780** [comment]
I agree. 

Sent from Yahoo Mail on Android 
 
  On Thu, Mar 9, 2017 at 3:57 PM, David Ketcheson<notifications@github.com> wrote:   
Some notebooks -- like the 3 in the notebooks/geoclaw folder -- exist both in clawpack/doc and clawpack/apps. This duplication is problematic since it means twice the work in maintaining them, if we remember to maintain them at all. Note that at least one of these notebooks is currently broken (see #60).

I suggest that any given notebook be kept either in doc (if it serves primarily as documentation) or in apps (if it does not), but not both.

**Comment by ketch** [comment]
After more consultation with @rjleveque, I'm going to remove those 3 Geoclaw notebooks from apps, but leave the AMR example.  The latter appears in the docs (with output), but won't run without the additional files that are in its apps directory.  It's also duplicated (but without the notebook) in amrclaw/examples.  I'm not a fan of this duplication but I'm fine with leaving it alone.

**Comment by mandli** [comment]
Should we close this issue or leave it open pending a better AMRClaw notebook solution?

**Comment by ketch** [comment]
I think we've agreed to live with the remaining duplication, so I will close this.
